# Generated by Django 2.0.6 on 2018-06-23 11:48

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('osmapp', '0001_initial'), ('osmapp', '0002_post'), ('osmapp', '0003_auto_20180622_2042'), ('osmapp', '0004_auto_20180622_2042'), ('osmapp', '0005_auto_20180622_2223')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('n', 'node'), ('w', 'way'), ('r', 'relation')], max_length=1)),
                ('role', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('uid', models.IntegerField(null=True)),
                ('user', models.TextField(null=True)),
                ('visible', models.BooleanField()),
                ('version', models.IntegerField(null=True)),
                ('changeset', models.IntegerField(null=True)),
                ('incomplete', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OSM_Relation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('uid', models.IntegerField(null=True)),
                ('user', models.TextField(null=True)),
                ('visible', models.BooleanField()),
                ('version', models.IntegerField(null=True)),
                ('changeset', models.IntegerField(null=True)),
                ('incomplete', models.BooleanField(default=False)),
                ('member_nodes_rel', models.ManyToManyField(through='osmapp.MemberRelation', to='osmapp.Node')),
                ('member_relations_rel', models.ManyToManyField(through='osmapp.MemberRelation', to='osmapp.OSM_Relation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='osmapp.KeyValueString')),
                ('value', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='osmapp.KeyValueString')),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('uid', models.IntegerField(null=True)),
                ('user', models.TextField(null=True)),
                ('visible', models.BooleanField()),
                ('version', models.IntegerField(null=True)),
                ('changeset', models.IntegerField(null=True)),
                ('incomplete', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmapp.Node')),
                ('way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmapp.Way')),
            ],
        ),
        migrations.AddField(
            model_name='way',
            name='nodes',
            field=models.ManyToManyField(related_name='nodes_in_way', through='osmapp.WN', to='osmapp.Node'),
        ),
        migrations.AddField(
            model_name='way',
            name='tags',
            field=models.ManyToManyField(blank=True, to='osmapp.Tag'),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='member_ways_rel',
            field=models.ManyToManyField(through='osmapp.MemberRelation', to='osmapp.Way'),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='osmapp.Tag'),
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(blank=True, to='osmapp.Tag'),
        ),
        migrations.AddField(
            model_name='memberrelation',
            name='member_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osmapp.Node'),
        ),
        migrations.AddField(
            model_name='memberrelation',
            name='member_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberrelation_member_relations_rel', to='osmapp.OSM_Relation'),
        ),
        migrations.AddField(
            model_name='memberrelation',
            name='member_way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osmapp.Way'),
        ),
        migrations.AddField(
            model_name='memberrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmapp.OSM_Relation'),
        ),
        migrations.AlterUniqueTogether(
            name='wn',
            unique_together={('node', 'way', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('key', 'value')},
        ),
        migrations.CreateModel(
            name='FeedBounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=200)),
                ('outer_bound', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=20, max_digits=50), size=None), blank=True, size=None)),
                ('inner_bound', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=20, max_digits=50), size=None), blank=True, size=None)),
            ],
        ),
    ]
