# Generated by Django 2.0.6 on 2018-06-23 13:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmapp', '0001_squashed_0005_auto_20180622_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbounds',
            name='id',
        ),
        migrations.AddField(
            model_name='feedbounds',
            name='feed_id',
            field=models.IntegerField(blank=True, default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbounds',
            name='inner_bound',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='feedbounds',
            name='outer_bound',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, size=None),
        ),
    ]
