# Generated by Django 2.0.6 on 2018-06-24 10:13

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField(blank=True)),
                ('operator_name', models.CharField(max_length=200)),
                ('outer_bound', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, size=None)),
                ('inner_bound', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        ),
    ]
