# Generated by Django 2.0.6 on 2018-07-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmapp', '0001_squashed_0002_auto_20180627_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='way',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
