# Generated by Django 2.0.6 on 2018-06-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmapp', '0002_bounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounds',
            name='inner_bound',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
