# Generated by Django 2.0.6 on 2018-06-22 20:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmapp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=200)),
                ('outer_bound', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, size=None)),
                ('inner_bound', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
