# Generated by Django 2.0.6 on 2018-06-22 22:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmapp', '0004_auto_20180622_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbounds',
            name='inner_bound',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=20, max_digits=50), size=None), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='feedbounds',
            name='outer_bound',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=20, max_digits=50), size=None), blank=True, size=None),
        ),
    ]
