# Generated by Django 2.0.6 on 2018-06-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtfsform',
            name='feed',
        ),
    ]
