# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 11:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osm_relation',
            name='changeset',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gs.Tag'),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='uid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='user',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='osm_relation',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='way',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='member_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gs.Node'),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='member_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberrelation_member_relations_rel', to='gs.OSM_Relation'),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='member_way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gs.Way'),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='role',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='sequence',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberrelation',
            name='type',
            field=models.CharField(blank=True, choices=[('n', 'node'), ('w', 'way'), ('r', 'relation')], max_length=1),
        ),
        migrations.AlterField(
            model_name='node',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='osm_relation',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='way',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
