# Generated by Django 2.0.6 on 2018-07-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0001_squashed_0002_auto_20180629_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtfsform',
            name='feed',
        ),
        migrations.AddField(
            model_name='gtfsform',
            name='feed_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
