# Generated by Django 2.0.6 on 2018-06-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0001_initial'),
        ('gs', '0002_remove_gtfsform_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtfsform',
            name='feed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Feed'),
        ),
    ]
