# Generated by Django 2.0.6 on 2018-07-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0002_auto_20180722_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtfsform',
            name='gtfs_tag',
        ),
        migrations.RemoveField(
            model_name='gtfsform',
            name='osm_tag',
        ),
    ]
