# Generated by Django 2.0.5 on 2018-05-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0002_auto_20180502_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.IntegerField()),
                ('key_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(max_length=20)),
                ('member_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('uid', models.IntegerField()),
                ('user', models.CharField(max_length=20)),
                ('version', models.IntegerField()),
                ('changeset', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('rel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('uid', models.IntegerField()),
                ('user', models.CharField(max_length=20)),
                ('version', models.IntegerField()),
                ('changeset', models.IntegerField()),
                ('mem_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gs.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('key_ref', models.ManyToManyField(blank=True, to='gs.Key')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_id', models.IntegerField()),
                ('value_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('way_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('uid', models.IntegerField()),
                ('user', models.CharField(max_length=20)),
                ('version', models.IntegerField()),
                ('changeset', models.IntegerField()),
                ('node_ref', models.ManyToManyField(blank=True, to='gs.Node')),
                ('tag_ref', models.ManyToManyField(blank=True, to='gs.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='SampleClass',
        ),
        migrations.AddField(
            model_name='tag',
            name='value_ref',
            field=models.ManyToManyField(blank=True, to='gs.Value'),
        ),
        migrations.AddField(
            model_name='relation',
            name='tag_ref',
            field=models.ManyToManyField(blank=True, to='gs.Tag'),
        ),
        migrations.AddField(
            model_name='node',
            name='tag_ref',
            field=models.ManyToManyField(blank=True, to='gs.Tag'),
        ),
        migrations.AddField(
            model_name='member',
            name='node_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gs.Node'),
        ),
        migrations.AddField(
            model_name='member',
            name='way_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gs.Way'),
        ),
    ]
