# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0003_gtfsform'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtfsform',
            name='frequency',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AddField(
            model_name='gtfsform',
            name='gtfs_tag',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gtfsform',
            name='osm_tag',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gtfsform',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 24, 13, 7, 41, 794809, tzinfo=utc)),
        ),
    ]
