# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0004_auto_20180524_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtfsform',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gtfsform',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 24, 19, 23, 4, 617445, tzinfo=utc)),
        ),
    ]
