# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0005_auto_20180524_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtfsform',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
