# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0006_auto_20180526_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtfsform',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, default=3),
        ),
    ]
