# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0008_auto_20180531_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='geom',
            new_name='geome',
        ),
    ]
