# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0009_auto_20180601_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberrelation',
            name='member_node',
        ),
        migrations.RemoveField(
            model_name='memberrelation',
            name='member_relation',
        ),
        migrations.RemoveField(
            model_name='memberrelation',
            name='member_way',
        ),
        migrations.RemoveField(
            model_name='memberrelation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='osm_relation',
            name='member_nodes_rel',
        ),
        migrations.RemoveField(
            model_name='osm_relation',
            name='member_relations_rel',
        ),
        migrations.RemoveField(
            model_name='osm_relation',
            name='member_ways_rel',
        ),
        migrations.RemoveField(
            model_name='osm_relation',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='key',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
        migrations.RemoveField(
            model_name='way',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='way',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='wn',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='wn',
            name='node',
        ),
        migrations.RemoveField(
            model_name='wn',
            name='way',
        ),
        migrations.DeleteModel(
            name='KeyValueString',
        ),
        migrations.DeleteModel(
            name='MemberRelation',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='OSM_Relation',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Way',
        ),
        migrations.DeleteModel(
            name='WN',
        ),
    ]
