# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0016_remove_stop_point'),
        ('gs', '0010_auto_20180602_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtfsform',
            name='feed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Feed'),
        ),
    ]
