# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs', '0011_gtfsform_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtfsform',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
