# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 11:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multigtfs', '0012_auto_20180603_1240'),
        ('osmapp', '0003_auto_20180527_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMP_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('node_geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmapp.Node')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Stop')),
            ],
            options={
                'db_table': 'cmp_stop',
            },
        ),
    ]
