# Generated by Django 2.0.6 on 2018-07-01 18:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('compare', '0001_initial'), ('compare', '0002_osm_node_cmp'), ('compare', '0003_auto_20180701_1759'), ('compare', '0004_auto_20180701_1806')]

    initial = True

    dependencies = [
        ('osmapp', '0001_squashed_0002_auto_20180627_1205'),
        ('multigtfs', '0001_squashed_0001_initial'),
        ('multigtfs', '0001_initial'),
        ('osmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMP_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CMP_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('node_geom', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('type', models.CharField(max_length=10, null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmapp.Node')),
                ('stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Stop')),
            ],
            options={
                'db_table': 'cmp_stop',
            },
        ),
        migrations.CreateModel(
            name='itineraries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OSM_Node_CMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_type', models.CharField(blank=True, choices=[('NAME', 'name'), ('LOCATION', 'location')], max_length=10)),
                ('feed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Feed')),
                ('fixed_match', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to='multigtfs.Stop')),
                ('probable_matched_stops', models.ManyToManyField(blank=True, related_name='by_app', to='osmapp.Node')),
                ('gtfs_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Stop')),
            ],
        ),
    ]
