# Generated by Django 2.0.6 on 2018-07-30 17:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osmapp', '0002_auto_20180726_1532'),
        ('multigtfs', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMP_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CMP_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to='osmapp.Node')),
                ('gtfs_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='itineraries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Line_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('stop_id', models.CharField(blank=True, max_length=500, null=True)),
                ('stop_code', models.CharField(blank=True, max_length=500, null=True)),
                ('stop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_time_stop_seq', models.IntegerField(blank=True, null=True)),
                ('trip_extra_data', models.CharField(blank=True, max_length=500, null=True)),
                ('route_id_db', models.IntegerField(blank=True, null=True)),
                ('route_id', models.CharField(blank=True, max_length=500, null=True)),
                ('route_short_name', models.CharField(blank=True, max_length=500, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=500, null=True)),
                ('route_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('route_color', models.CharField(blank=True, max_length=500, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('all_node_info', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None), blank=True, null=True, size=None)),
                ('relation_info', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None), blank=True, null=True, size=None)),
            ],
        ),
    ]
