# Generated by Django 2.0.6 on 2018-06-19 18:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multigtfs', '0001_initial'),
        ('osmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMP_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CMP_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('node_geom', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
                ('type', models.CharField(max_length=10, null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmapp.Node')),
                ('stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Stop')),
            ],
            options={
                'db_table': 'cmp_stop',
            },
        ),
        migrations.CreateModel(
            name='itineraries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
