# Generated by Django 2.0.6 on 2018-07-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0001_squashed_0001_initial'),
        ('osmapp', '0001_squashed_0002_auto_20180627_1205'),
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSM_Node_CMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_type', models.CharField(blank=True, choices=[('NAME', 'name'), ('LOCATION', 'location')], max_length=10)),
                ('feed_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Feed')),
                ('fixed_match', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to='multigtfs.Stop')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmapp.Node')),
                ('probable_matched_stops', models.ManyToManyField(blank=True, related_name='by_app', to='multigtfs.Stop')),
            ],
        ),
    ]
