# Generated by Django 2.0.6 on 2018-07-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmp_stop',
            name='matching_type',
        ),
        migrations.RemoveField(
            model_name='cmp_stop',
            name='probable_matched_stops',
        ),
    ]
