# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 12:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cmp_stop',
            managers=[
                ('obejcts', django.db.models.manager.Manager()),
            ],
        ),
    ]
