# Generated by Django 2.0.6 on 2018-07-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_squashed_0004_auto_20180701_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmp_stop',
            name='node',
        ),
        migrations.RemoveField(
            model_name='cmp_stop',
            name='stop',
        ),
        migrations.DeleteModel(
            name='CMP_Stop',
        ),
    ]
