# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20180604_1215'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cmp_stop',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='cmp_stop',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cmp_stop',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmapp.Node'),
        ),
        migrations.AlterField(
            model_name='cmp_stop',
            name='stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Stop'),
        ),
    ]
