# Generated by Django 2.0.6 on 2018-07-30 17:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20180730_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation_data',
            name='rel_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
