# Generated by Django 2.0.6 on 2018-07-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_line_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_stop',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line_stop',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
