# Generated by Django 2.0.6 on 2018-08-02 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_relation_data_rel_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation_data',
            name='way_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
