# Generated by Django 2.0.6 on 2018-07-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0001_squashed_0001_initial'),
        ('compare', '0003_auto_20180701_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osm_node_cmp',
            name='node',
        ),
        migrations.AddField(
            model_name='osm_node_cmp',
            name='gtfs_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multigtfs.Stop'),
        ),
        migrations.AlterField(
            model_name='osm_node_cmp',
            name='probable_matched_stops',
            field=models.ManyToManyField(blank=True, related_name='by_app', to='osmapp.Node'),
        ),
    ]
