# Generated by Django 2.0.6 on 2018-07-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_auto_20180716_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_stop',
            name='route_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
