# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 18:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_auto_20180604_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmp_stop',
            name='node_geom',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='cmp_stop',
            name='stop_geom',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
