# Generated by Django 2.0.6 on 2018-08-03 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_relation_data_way_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation_data',
            name='all_node_info',
        ),
        migrations.RemoveField(
            model_name='relation_data',
            name='rel_ids',
        ),
        migrations.RemoveField(
            model_name='relation_data',
            name='relation_info',
        ),
        migrations.RemoveField(
            model_name='relation_data',
            name='way_ids',
        ),
        migrations.AddField(
            model_name='relation_data',
            name='nodes_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='relation_data',
            name='relations_info',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='relation_data',
            name='rels_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='relation_data',
            name='ways_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
