# Generated by Django 2.0.6 on 2018-07-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_auto_20180716_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_stop',
            name='trip_extra_data',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
