# Generated by Django 2.0.6 on 2018-07-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_auto_20180716_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_stop',
            name='stop_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='line_stop',
            name='trip_extra_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
