# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_auto_20180604_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmp_stop',
            old_name='stop_geom',
            new_name='geom',
        ),
    ]
