# Generated by Django 2.0.6 on 2018-07-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_auto_20180716_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_stop',
            name='stop_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
