# Generated by Django 2.0.6 on 2018-07-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0009_auto_20180716_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_stop',
            name='route_color',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='line_stop',
            name='route_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='line_stop',
            name='route_long_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='line_stop',
            name='route_text_color',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='line_stop',
            name='stop_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='line_stop',
            name='stop_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
