# Generated by Django 2.0.6 on 2018-07-27 11:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0013_remove_relation_data_ways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_data',
            name='nodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='relation_data',
            name='relations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
