# Generated by Django 2.0.6 on 2018-07-27 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0014_auto_20180727_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_data',
            name='nodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
