# Generated by Django 2.0.6 on 2018-07-29 04:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0016_auto_20180729_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation_data',
            name='all_node_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
    ]
