# Generated by Django 2.0.6 on 2018-07-29 05:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0017_relation_data_all_node_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_data',
            name='all_node_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
