# Generated by Django 2.0.6 on 2018-07-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0018_auto_20180729_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation_data',
            old_name='all_node_ids',
            new_name='all_node_info',
        ),
    ]
