# Generated by Django 2.0.6 on 2018-07-01 00:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_str', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('replace_str', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField(blank=True, null=True)),
                ('stop_id', models.CharField(blank=True, help_text='Unique identifier for a stop or station.', max_length=255, null=True)),
                ('stop_code', models.CharField(blank=True, help_text='Uniquer identifier (short text or number) for passengers.', max_length=255, null=True)),
                ('stop_name', models.CharField(blank=True, help_text='Name of stop in local vernacular.', max_length=255, null=True)),
                ('stop_desc', models.CharField(blank=True, help_text='Description of a stop.', max_length=255, null=True, verbose_name='description')),
                ('stop_zone', models.CharField(blank=True, help_text='Fare zone for a stop ID.', max_length=255, null=True)),
                ('stop_url', models.CharField(blank=True, help_text='URL for the stop', max_length=255, null=True)),
                ('stop_location_type', models.CharField(blank=True, help_text='Is this a stop or station?', max_length=255, null=True)),
                ('stop_parent_station', models.CharField(blank=True, help_text='The station associated with the stop', max_length=255, null=True)),
                ('stop_timezone', models.CharField(blank=True, help_text='Timezone of the stop', max_length=255, null=True)),
                ('agency_name', models.CharField(blank=True, help_text='Full name of the transit agency', max_length=255, null=True)),
                ('agency_id', models.CharField(blank=True, help_text='Unique identifier for transit agency', max_length=255, null=True)),
                ('agency_url', models.CharField(blank=True, help_text='URL of the transit agency', max_length=255, null=True)),
                ('agency_timezone', models.CharField(blank=True, help_text='Timezone of the agency', max_length=255, null=True)),
                ('agency_lang', models.CharField(blank=True, help_text='ISO 639-1 code for the primary language', max_length=2, null=True)),
                ('agency_phone', models.CharField(blank=True, help_text='Voice telephone number', max_length=255, null=True)),
                ('agency_fare_url', models.CharField(blank=True, help_text='URL for purchasing tickets online', max_length=255, null=True)),
            ],
        ),
    ]
