# Generated by Django 2.0.6 on 2018-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop_correspondence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id_key', models.IntegerField(blank=True)),
                ('stop_id_key', models.CharField(blank=True, help_text='Unique identifier for a stop or station.', max_length=255)),
                ('stop_code_key', models.CharField(blank=True, help_text='Uniquer identifier (short text or number) for passengers.', max_length=255)),
                ('stop_name_key', models.CharField(help_text='Name of stop in local vernacular.', max_length=255)),
                ('stop_desc_key', models.CharField(blank=True, help_text='Description of a stop.', max_length=255, verbose_name='description')),
                ('stop_zone_key', models.CharField(blank=True, help_text='Fare zone for a stop ID.', max_length=255)),
                ('stop_url_key', models.CharField(blank=True, help_text='URL for the stop', max_length=255)),
                ('stop_location_type_key', models.CharField(blank=True, choices=[('0', 'Stop'), ('1', 'Station')], help_text='Is this a stop or station?', max_length=1)),
                ('stop_parent_station_key', models.CharField(blank=True, help_text='The station associated with the stop', max_length=255)),
                ('stop_timezone_key', models.CharField(blank=True, help_text='Timezone of the stop', max_length=255)),
                ('agency_name_key', models.CharField(blank=True, help_text='Full name of the transit agency', max_length=255)),
                ('agency_id_key', models.CharField(blank=True, help_text='Unique identifier for transit agency', max_length=255)),
                ('agency_url_key', models.CharField(blank=True, help_text='URL of the transit agency', max_length=255)),
                ('agency_timezone_key', models.CharField(help_text='Timezone of the agency', max_length=255)),
                ('agency_lang_key', models.CharField(blank=True, help_text='ISO 639-1 code for the primary language', max_length=2)),
                ('agency_phone_key', models.CharField(blank=True, help_text='Voice telephone number', max_length=255)),
                ('agency_fare_url_key', models.CharField(blank=True, help_text='URL for purchasing tickets online', max_length=255)),
            ],
        ),
    ]
