# Generated by Django 2.0.6 on 2018-06-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stop_correspondence',
            new_name='Correspondence',
        ),
    ]
