# Generated by Django 2.0.6 on 2018-07-14 11:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence_Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, help_text='Full name of the transit agency', max_length=255, null=True)),
                ('agency_id', models.CharField(blank=True, help_text='Unique identifier for transit agency', max_length=255, null=True)),
                ('agency_url', models.CharField(blank=True, help_text='URL of the transit agency', max_length=255, null=True)),
                ('agency_timezone', models.CharField(blank=True, help_text='Timezone of the agency', max_length=255, null=True)),
                ('agency_lang', models.CharField(blank=True, help_text='ISO 639-1 code for the primary language', max_length=2, null=True)),
                ('agency_phone', models.CharField(blank=True, help_text='Voice telephone number', max_length=255, null=True)),
                ('agency_fare_url', models.CharField(blank=True, help_text='URL for purchasing tickets online', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondence_Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField(blank=True, null=True)),
                ('route_id', models.CharField(db_index=True, help_text='Unique identifier for route.', max_length=255)),
                ('agency', models.CharField(blank=True, max_length=50)),
                ('short_name', models.CharField(help_text='Short name of the route', max_length=63)),
                ('long_name', models.CharField(help_text='Long name of the route', max_length=255)),
                ('desc', models.CharField(blank=True, help_text='Long description of a route', max_length=50)),
                ('rtype', models.IntegerField(choices=[(0, 'Tram, Streetcar, or Light rail'), (1, 'Subway or Metro'), (2, 'Rail'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable car'), (6, 'Gondola or Suspended cable car'), (7, 'Funicular')], help_text='Type of transportation used on route', verbose_name='route type')),
                ('url', models.URLField(blank=True, help_text='Web page about for the route')),
                ('color', models.CharField(blank=True, help_text='Color of route in hex', max_length=6)),
                ('text_color', models.CharField(blank=True, help_text='Color of route text in hex', max_length=6)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
        ),
    ]
