# Generated by Django 2.0.6 on 2018-06-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0002_auto_20180626_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='stop_name_key',
            field=models.CharField(blank=True, help_text='Name of stop in local vernacular.', max_length=255),
        ),
    ]
