# Generated by Django 2.0.6 on 2018-06-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0003_auto_20180626_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='stop_location_type_key',
            field=models.CharField(blank=True, help_text='Is this a stop or station?', max_length=255),
        ),
    ]
