# Generated by Django 2.0.6 on 2018-07-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0004_auto_20180714_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence_route',
            name='rtype',
            field=models.CharField(help_text='Type of transportation used on route', max_length=50),
        ),
    ]
