# Generated by Django 2.0.6 on 2018-06-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0004_auto_20180626_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='agency_fare_url_key',
            field=models.CharField(blank=True, help_text='URL for purchasing tickets online', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='agency_id_key',
            field=models.CharField(blank=True, help_text='Unique identifier for transit agency', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='agency_lang_key',
            field=models.CharField(blank=True, help_text='ISO 639-1 code for the primary language', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='agency_name_key',
            field=models.CharField(blank=True, help_text='Full name of the transit agency', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='agency_phone_key',
            field=models.CharField(blank=True, help_text='Voice telephone number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='agency_timezone_key',
            field=models.CharField(blank=True, help_text='Timezone of the agency', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='agency_url_key',
            field=models.CharField(blank=True, help_text='URL of the transit agency', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='feed_id_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='stop_code_key',
            field=models.CharField(blank=True, help_text='Uniquer identifier (short text or number) for passengers.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='stop_desc_key',
            field=models.CharField(blank=True, help_text='Description of a stop.', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='stop_id_key',
            field=models.CharField(blank=True, help_text='Unique identifier for a stop or station.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='stop_location_type_key',
            field=models.CharField(blank=True, help_text='Is this a stop or station?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='stop_name_key',
            field=models.CharField(blank=True, help_text='Name of stop in local vernacular.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='stop_parent_station_key',
            field=models.CharField(blank=True, help_text='The station associated with the stop', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='stop_timezone_key',
            field=models.CharField(blank=True, help_text='Timezone of the stop', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='stop_url_key',
            field=models.CharField(blank=True, help_text='URL for the stop', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='stop_zone_key',
            field=models.CharField(blank=True, help_text='Fare zone for a stop ID.', max_length=255, null=True),
        ),
    ]
