# Generated by Django 2.0.6 on 2018-06-27 20:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0005_auto_20180626_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_str', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('relace_str', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        ),
    ]
