# Generated by Django 2.0.6 on 2018-07-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0005_auto_20180714_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafield',
            name='feed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
