# Generated by Django 2.0.6 on 2018-07-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0006_extrafield_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence_agency',
            name='agency_fare_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence_agency',
            name='agency_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence_agency',
            name='agency_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence_agency',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence_agency',
            name='agency_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence_agency',
            name='agency_timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence_agency',
            name='agency_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence_route',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondence_route',
            name='desc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondence_route',
            name='long_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='correspondence_route',
            name='route_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='correspondence_route',
            name='rtype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondence_route',
            name='short_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='correspondence_route',
            name='text_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondence_route',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
