# Generated by Django 2.0.6 on 2018-06-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0006_conversion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondence',
            old_name='agency_fare_url_key',
            new_name='agency_fare_url',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='agency_id_key',
            new_name='agency_id',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='agency_lang_key',
            new_name='agency_lang',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='agency_name_key',
            new_name='agency_name',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='agency_phone_key',
            new_name='agency_phone',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='agency_timezone_key',
            new_name='agency_timezone',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='agency_url_key',
            new_name='agency_url',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='feed_id_key',
            new_name='feed_id',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='stop_code_key',
            new_name='stop_code',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='stop_desc_key',
            new_name='stop_desc',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='stop_id_key',
            new_name='stop_id',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='stop_location_type_key',
            new_name='stop_location_type',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='stop_name_key',
            new_name='stop_name',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='stop_parent_station_key',
            new_name='stop_parent_station',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='stop_timezone_key',
            new_name='stop_timezone',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='stop_url_key',
            new_name='stop_url',
        ),
        migrations.RenameField(
            model_name='correspondence',
            old_name='stop_zone_key',
            new_name='stop_zone',
        ),
    ]
