# Generated by Django 2.0.6 on 2018-06-28 18:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0007_auto_20180627_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='present_str',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='relace_str',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
