# Generated by Django 2.0.6 on 2018-06-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0008_auto_20180628_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversion',
            old_name='relace_str',
            new_name='replace_str',
        ),
    ]
