# Generated by Django 2.0.6 on 2018-07-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0008_auto_20180715_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence_agency',
            name='feed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
