# Generated by Django 2.0.6 on 2018-08-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversionapp', '0010_auto_20180720_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondence',
            name='agency_fare_url',
        ),
        migrations.RemoveField(
            model_name='correspondence',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='correspondence',
            name='agency_lang',
        ),
        migrations.RemoveField(
            model_name='correspondence',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='correspondence',
            name='agency_phone',
        ),
        migrations.RemoveField(
            model_name='correspondence',
            name='agency_timezone',
        ),
        migrations.RemoveField(
            model_name='correspondence',
            name='agency_url',
        ),
    ]
