# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 18:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0002_remove_stop_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shape',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='shapepoint',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='shape',
        ),
        migrations.AddField(
            model_name='stop',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default='', help_text='WGS 84 latitude/longitude of stop or station', srid=4326),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
        migrations.DeleteModel(
            name='ShapePoint',
        ),
    ]
