# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 18:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0003_auto_20180602_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default='', help_text='WGS 84 latitude/longitude of stop or station', srid=4326),
        ),
    ]
