# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 21:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0006_auto_20180602_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='', help_text='Added by srikant for testing', srid=4326),
            preserve_default=False,
        ),
    ]
