# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 21:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0007_stop_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Added by srikant for testing', null=True, srid=4326),
        ),
    ]
