# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 21:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0008_auto_20180602_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='geom',
        ),
        migrations.AddField(
            model_name='stop',
            name='geome',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Added by srikant for testing', null=True, srid=4326),
        ),
    ]
