# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 21:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0009_auto_20180602_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='geome',
        ),
        migrations.AddField(
            model_name='stop',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Add for test', null=True, srid=4326),
        ),
    ]
