# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0010_auto_20180602_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='geom',
        ),
    ]
