# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0011_remove_stop_geom'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agency',
            table='gtfs_agency',
        ),
        migrations.AlterModelTable(
            name='block',
            table='gtfs_block',
        ),
        migrations.AlterModelTable(
            name='fare',
            table='gtfs_fare',
        ),
        migrations.AlterModelTable(
            name='farerule',
            table='gtfs_fare_rules',
        ),
        migrations.AlterModelTable(
            name='feed',
            table='gtfs_feed',
        ),
        migrations.AlterModelTable(
            name='feedinfo',
            table='gtfs_feed_info',
        ),
        migrations.AlterModelTable(
            name='frequency',
            table='gtfs_frequency',
        ),
        migrations.AlterModelTable(
            name='route',
            table='gtfs_route',
        ),
        migrations.AlterModelTable(
            name='service',
            table='gtfs_service',
        ),
        migrations.AlterModelTable(
            name='servicedate',
            table='gtfs_service_date',
        ),
        migrations.AlterModelTable(
            name='stop',
            table='gtfs_stop',
        ),
        migrations.AlterModelTable(
            name='stoptime',
            table='gtfs_stop_time',
        ),
        migrations.AlterModelTable(
            name='transfer',
            table='gtfs_transfer',
        ),
        migrations.AlterModelTable(
            name='trip',
            table='gtfs_trip',
        ),
        migrations.AlterModelTable(
            name='zone',
            table='gtfs_zone',
        ),
    ]
