# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 21:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0012_auto_20180603_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(help_text='WGS 84 latitude/longitude of stop or station', null=True, srid=4326),
        ),
    ]
