# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multigtfs', '0013_stop_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='point',
        ),
    ]
